### ISSUE TITLE
Hi!

### ISSUE THREAD

**Issue by CryptoAmanda** [secret-bitcoin-login/indigent-android-bitcoin#1]
I'm not super-experienced with GitHub and wasn't sure how to contact you. 

Yes, I'd be interested to receive a phone as you've described in your project description, and I'd certainly be happy to report about it all on The Daily Decrypt.

I suppose we need to coordinate how I can give you shipping and other information. Do you have a PGP key, or do you use Telegram or something? I'm @amandabjohnson on Telegram, and my PGP key/email addy can be found at http://keybase.io/cryptoamanda.

Cheers,
Amanda B. Johnson

**Comment by secret-bitcoin-login** [comment]
Sorry for the delay - I'm very interested in keybase.io, could you share an invitation with me at secret.bitcoin.login@gmail.com?

**Comment by CryptoAmanda** [comment]
Sent! :) Look forward to hearing from you.

-A

**Comment by secret-bitcoin-login** [comment]
wahoo! It took me a little time to get used to the control characters (apostrophe's and returns), but I think my third message was successful. I really appreciate the keybase invite!  Let me know if you didn't receive an _actual_ message.

**Comment by secret-bitcoin-login** [comment]
-----BEGIN PGP MESSAGE-----
Comment: https://keybase.io/download
Version: Keybase Go 1.0.5 (linux)

wcFMA0yZE1BpXbQwARAAjmjlCik4lsMM5Roaq9jEKLMtnJTToWjS7TD7UVZoS3XH
qmCodMY2uBdubU5oFItl38n+4YWDtHn710+5Cq8BZ/oApziP9ht+zirl3ri+jyLv
nId9Lx6AdjNXY7oY1x8BcKpiC41epAfcIKAfD9edWbtr+fFbdMGpRUGE2qjNBEmW
6JHrFwiyEKiRoYcuVOkxjs5KTdDEbTqSBIrxDKgAF4dLBxb1luyeEvAMsmtJdFhX
I3c/6Fu6UWy3Xu/aSbYJMI/bYFKnAaZGcUUIOqmSQhLd+dmx96hLIT7EbOs6p3dX
NKq7Mx18jQyl/5ZBXOFx9LrAVQBhh0JSD24P7rsjItnO0iQlLsdBJbOVVLN1JbVw
viOre7hr/4twdr0t+hQWC3nhAv/sJrk1HmWpv7YaSjt+ORR4JqmTpwhD20YyITNz
Kase/2PzSoz8mCC0wF6z7EfMxEohGkgqIFtBZbKwXs0tx1OHgWEcDQZX+kLG/KAs
dk/hZJH1BHpqUoiX6cz5XJTmlVpQcf0SWE/zE9tSo1RCgTQ/ZtX5kMe31EyF364L
s1EBrsvwFWTeCRHwtaB2smUZcirXAfD6nVhFU5nn9B6Yfe01eW2CpbuGGTO2XP0D
UDl5M+hARmk7EivdhPzLigHfMGMZL3qnDkr9OM5NDhongULWcMbbOnO1pAdp52jB
wEwDag2PbKAlu3sBCACaeMi3oG3PBYMnU+jNE4hC1RRtrhabV28oKQ+4atzilvqc
8wIyQyw9VAyHczwps6+rE2XMAOYi+E9KWpMgaTko6m2XGT2o7kZgKNHcR6wYDtQ/
DmALT2Dx1xhoeAJ/d7E8NmjoRCJcZp/99JjjL0XXXZBxLAzaWRycb7+tXDMpzTzy
qJDz1IW38ANINejAxfY5yDcz7WrqIgoN/1t6ZpXmoxzJm58rSqxP7Aj+OYZmgJ6G
YJFLEITYWm+ofe41/xVCpuWM1zS1YZuC56x1szQHz2cQL0w/b/Q7/kTsIUviGkOH
uDVZqc9Ny2jp7BNteI/+Wu87ZqB+iPRZ8i+yYVSH0uAB5CJSAKVJVdD4qEpn75Ul
qYfhWgfg2+D84Y6V4GXiT9dQCOB76SlrS6reIRvQ1s2f35NCwyCWnRBcqO5M4Vvl
wXL12pul4ZTe+JQZ+4lA5Q4+NYZBGEWiiFG4cO1EKOacMA6ENtX+CT4FSZvUsT+Z
adhzSK044c++uovne12vWteHW3C/WCrUsF4fmXA8IkKGBaVE5JyR/KHkJfxdO8tx
XaoMyPqYC0Rsg8yjvt607NsURs7Cg7kQUB7XRd6gPLgBd3bPwUNOFBsRdzjne+O6
LxdNG3ZUNSwkKBg9hH3izCsnwrfo68JcOC+rfM6yUMOEc9FmtUJyTNXdL7Jg7liw
8yw6yNgVN1Yyw63umf77IYkpQur+W2TjxxonkXcjtQ+KuQh9aJPgkQHQkvmlA1Hj
FSJJx/m80a8ks7pz7GiN3+V+gc/VzjwFGyR/iFLK3cB1fEVB1iXdQ04AziSrGBXh
Q1wNzZtiC3Cd18ck1aME1xU5dRGvQBgXzHcXAFrl+b03+cMq3EBXS1c8FjCz2qCt
n71doW8ejQywA5Sy2AXbjTC3p0pKL/tDkdNNjvCb6c0JEauU2hd7u0n4+oXx2HiD
biB780Ds43PWV9hxwFeM/gkeZNectcARxH4VfadLdfCu52LPnp/NZDbFnwCOpu31
rOeoCGE3NEUtBj8AQzZl1Ytx+vgcmlr68JOEfjUlL2GLcHOsCHP2Pns/z/iily+Y
1TjxLGZj4GroCnQmI2tsNKGEnxSmCzRdESwzB+WHEmP03GUX2tBNegjN9/iXPJj1
w+hm7K6ObDf+om+cMvVc6Pv5KGptkP75VD5NV/ZIX/O08pGqHTywd1t/4GRQ2gtE
eoRJBMhcRPxoh0bns6/g5HcmnHv14f33IatbGvDAGE4YwOkvMnXR+yPxmlVLk9Ih
XjgQRTEVfSW27CbxfWD702jbCHYBW654ck3GlBPquJz867J5zrW/BvJn0CEttuBn
rb3PNhlWfc3UEoJvMT3Pz7y9cPrqz2pK9C20ggmAY1IFXTQDvoE1na0Gy7AlTz7r
i2SubuhqqT7YKuti1oavoGlx8+5pF7/h6eB25ZRj1s0o26QwiMbdCARZtquA0kAc
dK05V4K5ulYRWXWk4PHk69O8/fyueCQeznrxjMrpdeDf4tjWlPHgp+GkfODG4E7g
DuSMXVBMMw8rx8rigcZzsnQQ4pxt5Kzh+i0A
=SUye
-----END PGP MESSAGE-----
