### ISSUE TITLE
Provide an offline maps app

### ISSUE THREAD

**Issue by tommorris** [secret-bitcoin-login/indigent-android-bitcoin#3]
There are a variety of maps apps (often using OpenStreetMap) that let you download an area of map for offline use. They have the potential to help the recipients of the phones find homeless shelters, food, transport and other useful services. You might want to add one to your phones.

**Comment by secret-bitcoin-login** [comment]
That's an EXCELLENT suggestion. I'll add it the next time I update the README.md. Thank you.

**Comment by secret-bitcoin-login** [comment]
Thanks again, I added maps.
